spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 10.0.0.70:9092,10.0.0.70:9093,10.0.0.70:9094
    bootstrap-servers: 10.0.0.70:9092,10.0.0.70:9093,10.0.0.70:9094
    topic:
      Name: topic1 #自定义topic名称
      numPartitions: 2  #自定义分区
      replicationFactor: 2 #自定义副本

    consumer:
      group-id: group1
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer